### ISSUE TITLE
numpy.float deprecated

### ISSUE THREAD

**Issue by bezborodow** [hwengineer/rf_linkbudget#1]
AttributeError: module 'numpy' has no attribute 'float'

**Comment by bezborodow** [comment]
See pull request #2.

**Comment by hwengineer** [comment]
merged your updates.
Thanks for sharing your work!

I didn't work on that for a long time, I'm glad that someone thinks it's useful.

**Comment by bezborodow** [comment]
Thanks. Did you feel comfortable releasing the updated version 1.1.7 on PyPI?

https://pypi.org/project/rf-linkbudget/

If you need help with package maintenance, let me know.

**Comment by hwengineer** [comment]
Hi, I actually thought it would update it automatically.
But as I saw my hole infrastructure is deactivated. I have to setup all the secrets in Github and pypi, also I must rework the pypi deploy script... Currently everything is out-of-sync or deleted....
I will update it, and then also pypi will be updated ;) 

If you want to help, I don't say no :P

**Comment by hwengineer** [comment]
Hurray!
It works again ;) 
Package successfully published!

**Comment by hwengineer** [comment]
readthedocs... still failes, I have to look into that

**Comment by hwengineer** [comment]
done, now also readthedocs works fine again.
They changed their yaml syntax over the years
